# Generated by Django 6.0.6 on 2026-06-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('imports', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate', to='imports.importjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_sku', models.CharField(blank=True, max_length=128)),
                ('raw_name', models.CharField(max_length=512)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('material_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('installation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('matching_status', models.CharField(choices=[('not_processed', 'Not processed'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('no_match', 'No match'), ('manual', 'Manual')], default='not_processed', max_length=32)),
                ('matching_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimate')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['name'], name='estimates_e_name_d47c36_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['created_at'], name='estimates_e_created_f19dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['estimate'], name='estimates_e_estimat_5eaaaa_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['raw_sku'], name='estimates_e_raw_sku_6e0151_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['raw_name'], name='estimates_e_raw_nam_f62574_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['matching_status'], name='estimates_e_matchin_fbf96f_idx'),
        ),
    ]
