# Generated by Django 6.0.6 on 2026-06-20 12:38

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("imports", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_list",
                        to="imports.importjob",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_sku", models.CharField(blank=True, max_length=128)),
                ("supplier_name", models.CharField(max_length=512)),
                ("unit", models.CharField(blank=True, max_length=64)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prices.pricelist",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_price_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="pricelist",
            index=models.Index(
                fields=["supplier"], name="prices_pric_supplie_b0ebad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricelist",
            index=models.Index(
                fields=["uploaded_at"], name="prices_pric_uploade_1ade30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpriceitem",
            index=models.Index(
                fields=["price_list"], name="prices_supp_price_l_71754d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpriceitem",
            index=models.Index(
                fields=["supplier_sku"], name="prices_supp_supplie_0c68a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpriceitem",
            index=models.Index(
                fields=["supplier_name"], name="prices_supp_supplie_7a6ed7_idx"
            ),
        ),
    ]
