# Generated by Django 6.0.6 on 2026-06-20 12:38

import apps.imports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.imports.models.import_file_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('price_list', 'Price list'), ('estimate', 'Estimate')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='imports.importfile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['import_type'], name='imports_imp_import__62342d_idx'), models.Index(fields=['status'], name='imports_imp_status_b5f1b5_idx'), models.Index(fields=['created_at'], name='imports_imp_created_2e10b1_idx')],
            },
        ),
    ]
